overrides:
  superstatic>re2: '-'
  '@webgpu/types': '-'
patchedDependencies:
  pixi.js@8.18.1: patches/pixi.js@8.18.1.patch
  react-switch: patches/react-switch.patch
  ts-jest@29.4.9: patches/ts-jest@29.4.9.patch
allowBuilds:
  argon2: true
  unrs-resolver: true
  core-js-pure: false

updateNotifier: false
strictPeerDependencies: true
allowUnusedPatches: false
verifyDepsBeforeRun: error
injectWorkspacePackages: false
forceLegacyDeploy: true
nodeOptions: --no-warnings=ExperimentalWarning --experimental-vm-modules

packages:
  - pandora-common
  - pandora-server-directory
  - pandora-server-shard
  - pandora-client-web
  - pandora-tests
