overrides:
  superstatic>re2: '-'
  '@webgpu/types': '-'
patchedDependencies:
  pixi.js: patches/pixi.js.patch
  react-switch: patches/react-switch.patch
allowBuilds:
  argon2: true
  unrs-resolver: true
  core-js-pure: false

allowUnusedPatches: false
forceLegacyDeploy: true
injectWorkspacePackages: false
minimumReleaseAge: 2880
nodeOptions: --no-warnings=ExperimentalWarning --experimental-vm-modules
strictPeerDependencies: true
updateNotifier: false
verifyDepsBeforeRun: error

packages:
  - pandora-common
  - pandora-server-directory
  - pandora-server-shard
  - pandora-client-web
  - pandora-tests
