name: Automation (Auto-approve)

on:
  # Triggers the workflow on any pull request (but runs in context of target branch, having a bit higher rights)
  pull_request_target:
    types:
      - opened

  automation:
    name: Automation tasks
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Auto-approve (Lead Developer)
        if: contains(fromJSON('["ace-1331", "ClaudiaMia", "elliesec", "Jomshir98", "Sekkmer"]'), github.event.pull_request.user.login)
        uses: hmarr/auto-approve-action@v3
        with:
          review-message: "PR is from a Lead Developer."

      - name: Auto-approve (Renovate)
        if: github.event.pull_request.user.login == 'renovate[bot]'
        uses: hmarr/auto-approve-action@v3
        with:
          review-message: "Automated dependency update."
