name: CD

on:
  # Triggers the workflow on push but only for the master branch
  push:
    branches: [ master ]
  # Triggers the workflow on any pull request
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker_build:
    name: Build server docker images
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Collect Docker metadata (pandora-server-directory)
        id: meta_directory
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/Project-Pandora-Game/Pandora-Server-Directory
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
      - name: Collect Docker metadata (pandora-server-shard)
        id: meta_shard
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/Project-Pandora-Game/Pandora-Server-Shard
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build (base)
        uses: docker/build-push-action@v4
        with:
          context: .
          target: builder
          push: false
      - name: Build (pandora-server-directory)
        uses: docker/build-push-action@v4
        with:
          context: .
          target: pandora-server-directory
          push: false
          # For when we will want CD too:
          # push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_directory.outputs.tags }}
          labels: ${{ steps.meta_directory.outputs.labels }}
      - name: Build (pandora-server-shard)
        uses: docker/build-push-action@v4
        with:
          context: .
          target: pandora-server-shard
          push: false
          # For when we will want CD too:
          # push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_shard.outputs.tags }}
          labels: ${{ steps.meta_shard.outputs.labels }}
