
name: PR

on:
  # Triggers the workflow on any pull request (but runs in context of target branch, having a bit higher rights)
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  title:
    name: Validate PR title
    runs-on: ubuntu-latest

    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          headerPattern: '^\[(\w*)\]:?\s*(.*)$'
          headerPatternCorrespondence: type, subject
          types: |
            FEATURE
            ADD
            CHANGE
            REMOVE
            FIX
            REFACTOR
            DEV
            CHORE

  automation:
    name: Automation tasks
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Auto-approve (Lead Developer)
        if: contains(fromJSON('["ace-1331", "ClaudiaMia", "elliesec", "Jomshir98", "Sekkmer"]'), github.actor)
        uses: hmarr/auto-approve-action@v3
        with:
          review-message: "PR is from a Lead Developer."

      - name: Auto-approve (Renovate)
        if: github.actor == 'renovate[bot]'
        uses: hmarr/auto-approve-action@v3
        with:
          review-message: "Automated dependency updates only need a single review."
